return {
  {
    title = "The Art of Computer Programming, Volumes 1-3",
    url = "http://amzn.to/YEZhFV",
    cover = {amazon = "41c-uUIgtyL"},
    authors = {"Donald E. Knuth"},
  },
  {
    title = "Artificial Intelligence: A Modern Approach",
    url = "http://amzn.to/14mN24u",
    cover = {amazon = "51bi4EnYE1L"},
    authors = {"Stuart J. Russell", "Peter Norvig"},
  },
  {
    title = "Beautiful Data",
    url = "http://amzn.to/XAd0Mu",
    cover = {amazon = "51c0tVjpW6L"},
    authors = {"Toby Segaran", "Jeff Hammerbacher"},
  },
  {
    title = "Programming Collective Intelligence",
    url = "http://amzn.to/178JZIS",
    cover = {amazon = "512bQudA%2BXL"},
    authors = {"Toby Segaran"},
  },
  {
    title = "Operating Systems Design and Implementation (3rd Edition)",
    url = "http://amzn.to/YF3jhA",
    cover = {amazon = "3125C47MR4L"},
    authors = {"Andrew S. Tanenbaum"},
  },
  {
    title = "Distributed Systems: Principles and Paradigms",
    url = "http://amzn.to/YF3GsD",
    cover = {amazon = "518hGvqORpL"},
    authors = {"Andrew S Tanenbaum", "Maarten van Steen"},
  },
  {
    title = "Language Implementation Patterns",
    url = "http://amzn.to/ZUgTZ0",
    cover = {amazon = "51BxY-%2B4G2L"},
    authors = {"Terence Parr"},
  },
  {
    title = "Structure and Interpretation of Computer Programs",
    url = "http://amzn.to/ZUgYfw",
    cover = {amazon = "41AJV8G0ZTL"},
    authors = {"Harold Abelson", "Gerald Jay Sussman"},
  },
  {
    title = "Masterminds of Programming",
    url = "http://amzn.to/10UTE3u",
    cover = {amazon = "51xuCNgNYHL"},
    authors = {"Federico Biancuzzi", "Chromatic"},
  },
  {
    title = "Beautiful Code",
    url = "http://amzn.to/111uDp5",
    cover = {amazon = "41jlLBcyDbL"},
    authors = {"Andy Oram", "Elliote Harold"},
  },
  {
    title = "The Art of UNIX Programming",
    url = "http://amzn.to/YF5gdZ",
    cover = {amazon = "51iyn7kz0uL"},
    authors = {"Eric S. Raymond"},
  },
  {
    title = "The Architecture of Open Source Applications",
    url = "http://amzn.to/YF5kKE",
    cover = {amazon = "51bBJGjs1PL"},
    authors = {"various"},
  },
  {
    title = "TCP/IP Guide: A Comprehensive, Illustrated Internet Protocols Reference",
    url = "http://amzn.to/Zq1bpw",
    cover = {amazon = "51x3aLlfAGL"},
    authors = {"Charles M. Kozierok"},
  },
  {
    title = "Coders at Work: Reflections on the Craft of Programming",
    url = "http://amzn.to/128nzI9",
    cover = {amazon = "41JzhuA--iL"},
    authors = {"Peter Seibel"},
  },
  {
    title = "Scalable Internet Architectures",
    url = "http://amzn.to/Zq1l06",
    cover = {amazon = "51lPir-0DtL"},
    authors = {"Theo Schlossnagle"},
  },
  {
    title = "The Pragmatic Programmer: From Journeyman to Master",
    url = "http://amzn.to/11cCdwH",
    cover = {amazon = "41F1cZImneL"},
    authors = {"Andrew Hunt"},
  },
  {
    title = "Effective Programming",
    url = "http://amzn.to/Zq1zVc",
    cover = {amazon = "51RB0YekufL"},
    authors = {"Jeff Atwood"},
  },
  {
    title = "Working with TCP Sockets",
    url = "http://amzn.to/131eCQI",
    cover = {amazon = "51uNC60Jm4L"},
    authors = {"Jesse Storimer"},
  },
  {
    title = "RESTful Web Services Cookbook",
    url = "http://amzn.to/17nHJmF",
    cover = {amazon = "51mqLZ5TBDL"},
    authors = {"Subbu Allamaraju"},
  },
  {
    title = "Seven Concurrency Models in Seven Weeks",
    url = "http://amzn.to/18qdPMb",
    cover = {amazon = "41ezh1bNKPL"},
    authors = {"Paul Butcher"},
  },
  {
    title = "The Senior Software Engineer",
    url = "http://theseniorsoftwareengineer.com/",
    cover = "imgs/senior.jpg",
    authors = {"David Bryant Copeland"},
  },
  {
    title = "Enterprise Integration Patterns",
    url = "http://amzn.to/18DwAPz",
    cover = {amazon = "51eqtvacK7L"},
    authors = {"Gregor Hohpe"},
  },
  {
    title = "Thinking in Systems: A Primer ",
    url = "http://amzn.to/1jFonZZ",
    cover = {amazon = "51NNRZBJ%2BsL"},
    authors = {"Donella Meadows"},
  },
  {
    title = "Introduction to Algorithms",
    url = "http://amzn.to/1rvwbb0",
    cover = {amazon = "41gI2CnLIwL"},
    authors = {"Thomas H. Cormen"},
  },
  {
    title = "Lua 5.1 Reference Manual",
    url = "http://amzn.to/10UUFIS",
    cover = {amazon = "31IcBV2gSqL"},
    authors = {"Roberto Ierusalimschy", "Luiz Henrique de Figueiredo", "Waldemar Celes"},
  },
  {
    title = "Programming Perl, 3rd edition",
    url = "http://amzn.to/10UUSvN",
    cover = {amazon = "51s5OsOQEvL"},
    authors = {"Larry Wall", "Tom Christiansen", "Jon Orwant"},
  },
  {
    title = "Programming Perl, 4th edition",
    url = "http://amzn.to/1171LKJ",
    cover = {amazon = "51yRdpS4yxL"},
    authors = {"Larry Wall", "Tom Christiansen", "Jon Orwant", "Brian D. Foy"},
  },
  {
    title = "Postfix: The Definitive Guide",
    url = "http://amzn.to/128p7lz",
    cover = {amazon = "51iXWdOFNZL"},
    authors = {"Kyle D. Dent"},
  },
  {
    title = "Land of Lisp",
    url = "http://amzn.to/157WBmR",
    cover = {amazon = "515ZuOjktML"},
    authors = {"Conrad Barski"},
  },
  {
    title = "C in a Nutshell",
    url = "http://amzn.to/Zq2uos",
    cover = {amazon = "51Rrc5DbMkL"},
    authors = {"Peter Prinz", "Tony Crawford"},
  },
  {
    title = "An Introduction to Programming in Go",
    url = "http://amzn.to/ZUi62t",
    cover = {amazon = "51h187HFm4L"},
    authors = {"Caleb Doxsey"},
  },
  {
    title = "tmux: Productive Mouse-Free Development",
    url = "http://amzn.to/14mZ1ii",
    cover = {amazon = "41n-bcndjdL"},
    authors = {"Brian P. Hogan"},
  },
  {
    title = "Programming in Lua, 3rd Edition",
    url = "http://amzn.to/1316ySR",
    cover = {amazon = "41AesdO8MzL"},
    authors = {"Roberto Ierusalimschy"},
  },
  {
    title = "Developing Mobile Games with Moai SDK",
    url = "http://amzn.to/1317E17",
    cover = {amazon = "51norGzt4mL"},
    authors = {"Francisco Tufró"},
  },
  {
    title = "Learn You a Haskell for Great Good!",
    url = "http://amzn.to/1c1Kpba",
    cover = {amazon = "41gFvETJlGL"},
    authors = {"Miran Lipovaca"},
  },
  {
    title = "Rust for Rubyists",
    url = "http://www.rustforrubyists.com/",
    cover = "imgs/placeholder.jpg",
    authors = {"Steve Klabnik"},
  },
  {
    title = "The Linux Programming Interface",
    url = "http://amzn.to/1hT71Je",
    cover = {amazon = "51--kb%2B6axL"},
    authors = {"Michael Kerrisk"},
  },
  {
    title = "Human JavaScript",
    url = "http://humanjavascript.com/",
    cover = "imgs/humanjs.jpg",
    authors = {"Henrik Joreteg"},
  },
  {
    title = "The Hacker's Guide to Python ",
    url = "http://amzn.to/1n73D0Y",
    cover = {amazon = "41xRZwJBsiL"},
    authors = {"Julien Danjou"},
  },
  {
    title = "The Inmates Are Running the Asylum",
    url = "http://amzn.to/Zqb0nq",
    cover = {amazon = "51xNkNwTDhL"},
    authors = {"Alan Cooper"},
  },
  {
    title = "The Substance of Style",
    url = "http://amzn.to/Yn3Jop",
    cover = {amazon = "41GMD9KV9FL"},
    authors = {"Virginia Postrel"},
  },
  {
    title = "Thinking Like a Designer",
    url = "http://amzn.to/111N9NZ",
    cover = {amazon = "51Xi8HTsvoL"},
    authors = {"Sacha Greif"},
  },
  {
    title = "Design Is a Job",
    url = "http://amzn.to/XAo10r",
    cover = {amazon = "21RZiSt7zeL"},
    authors = {"Mike Monteiro"},
  },
  {
    title = "The Design of Design",
    url = "http://amzn.to/YFpaW5",
    cover = {amazon = "51HsSqoVCtL"},
    authors = {"Frederick P. Brooks"},
  },
  {
    title = "The Laws of Simplicity",
    url = "http://amzn.to/128BVse",
    cover = {amazon = "41V3zzQwb0L"},
    authors = {"John Maeda"},
  },
  {
    title = "The Little Black Book of Design",
    url = "http://amzn.to/11cSYb8",
    cover = {amazon = "21ZwE6Emg9L"},
    authors = {"Adam Judge"},
  },
  {
    title = "A Theory of Fun",
    url = "http://amzn.to/10FtJMT",
    cover = {amazon = "51CQ7BzS3JL"},
    authors = {"Raph Koster"},
  },
  {
    title = "Design Rules for Free-to-Play Games",
    url = "http://amzn.to/154RPV8",
    cover = {amazon = "41wm6ZXF%2BLL"},
    authors = {"Nicholas Lovell","Rob Fahey"},
  },
  {
    title = "This is Service Design Thinking",
    url = "http://amzn.to/15Jp8M7",
    cover = {amazon = "41PPjX4dA-L"},
    authors = {"Marc Stickdorn"},
  },
  {
    title = "Founders at Work",
    url = "http://amzn.to/Yn4oWW",
    cover = {amazon = "51UuMI8MieL"},
    authors = {"Jessica Livingston"},
  },
  {
    title = "The Lean Startup",
    url = "http://amzn.to/132XE3z",
    cover = {amazon = "51gn6AuFkNL"},
    authors = {"Eric Ries"},
  },
  {
    title = "The 4-Hour Workweek",
    url = "http://amzn.to/11cTzJW",
    cover = {amazon = "51G957Lf-1L"},
    authors = {"Timothy Ferriss"},
  },
  {
    title = "La création d'entreprise - 14ème édition",
    url = "http://amzn.to/128CCSd",
    cover = {amazon = "41-aYPwU8aL"},
    authors = {"Robert Papin"},
  },
  {
    title = "Rework",
    url = "http://amzn.to/11cU32I",
    cover = {amazon = "411kdTeJbpL"},
    authors = {"David Heinemeier Hansson", "Jason Fried"},
  },
  {
    title = "The Art Of The Start",
    url = "http://amzn.to/YFr09z",
    cover = {amazon = "41mb1dXtk3L"},
    authors = {"Guy Kawasaki"},
  },
  {
    title = "Reality Check",
    url = "http://amzn.to/111PgBp",
    cover = {amazon = "41T0FpCBGDL"},
    authors = {"Guy Kawasaki"},
  },
  {
    title = "The Mythical Man-Month, 2nd Edition",
    url = "http://amzn.to/YFrmNi",
    cover = {amazon = "513u5ErJOyL"},
    authors = {"Frederick P. Brooks"},
  },
   {
    title = "Start Small, Stay Small",
    url = "http://amzn.to/Zqcoqc",
    cover = {amazon = "31p7nE9DwNL"},
    authors = {"Rob Walling"},
  },
  {
    title = "The Innovator's Dilemma",
    url = "http://amzn.to/YFrRXV",
    cover = {amazon = "51OW6BRj3kL"},
    authors = {"Clayton M. Christensen"},
  },
  {
    title = "European Founders at Work",
    url = "http://amzn.to/11cV4aZ",
    cover = {amazon = "51gDt6taG0L"},
    authors = {"Pedro Gairifo Santos"},
  },
  {
    title = "Only the Paranoid Survive",
    url = "http://amzn.to/ZUp33P",
    cover = {amazon = "51jfB%2BSvkiL"},
    authors = {"Andrew S. Grove"},
  },
  {
    title = "Managing Humans, 2nd Edition",
    url = "http://amzn.to/111QmNs",
    cover = {amazon = "51px%2BW3SA9L"},
    authors = {"Michael Lopp"},
  },
  {
    title = "The Leprechauns of Software Engineering",
    url = "https://leanpub.com/leprechauns",
    cover = "imgs/leprechauns.jpg",
    authors = {"Laurent Bossavit"},
  },
  {
    title = "Release It!: Design and Deploy Production-Ready Software",
    url = "http://amzn.to/YFtuEV",
    cover = {amazon = "41r%2B60K7UjL"},
    authors = {"Michael T. Nygard"},
  },
  {
    title = "APIs: A Strategy Guide",
    url = "http://amzn.to/10V6eQb",
    cover = {amazon = "51JX-MWB92L"},
    authors = {"Daniel Jacobson", "Greg Brail", "Dan Woods"},
  },
  {
    title = "The Art of Funding a Startup",
    url = "http://amzn.to/XLcu0p",
    cover = {amazon = "51C-xog3atL"},
    authors = {" Andrew Warner", "Paul Graham"},
  },
  {
    title = "The Chaos Scenario",
    url = "http://amzn.to/YFungK",
    cover = {amazon = "517tTMrKofL"},
    authors = {"Bob Garfield"},
  },
  {
    title = "Women Leaders at Work",
    url = "http://amzn.to/14ndBpZ",
    cover = {amazon = "514LuKlL%2B-L"},
    authors = {"Elizabeth Ghaffari"},
  },
  {
    title = "CTOs at Work",
    url = "http://amzn.to/YFuGZ1",
    cover = {amazon = "4127iTmQaiL"},
    authors = {"Scott Donaldson", "Stanley Siegel", "Gary Donaldson"},
  },
  {
    title = "Startups Open Sourced",
    url = "http://amzn.to/YFuXeh",
    cover = {amazon = "41KiuEtO6YL"},
    authors = {"Jared Tame"},
  },
  {
    title = "Great by Choice",
    url = "http://amzn.to/128FDCc",
    cover = {amazon = "41hG774Na8L"},
    authors = {"Jim Collins"},
  },
  {
    title = "Sell More Software: Website Conversion Optimization for Software Developers",
    url = "http://amzn.to/11dhwRa",
    cover = {amazon = "51XSxBSHhML"},
    authors = {"Patrick McKenzie"},
  },
  {
    title = "The Found a Business Book",
    url = "http://www.foundabusiness.com/",
    cover = "imgs/placeholder.jpg",
    authors = {"Jack Kaufman"},
  },
  {
    title = "Commitment",
    url = "http://amzn.to/131dJYB",
    cover = {amazon = "5101kebQqQL"},
    authors = {"Olav Maasen","Chris Matts","Chris Geary"},
  },
  {
    title = "Running Lean",
    url = "http://amzn.to/18xfzCx",
    cover = {amazon = "413wjRk5XrL"},
    authors = {"Ash Maurya"},
  },
  {
    title = "Gamers at Work",
    url = "http://amzn.to/12c6Ekl",
    cover = {amazon = "51Sly4b2U%2BL"},
    authors = {"Morgan Ramsay"},
  },
  {
    title = "The Lean Entrepreneur",
    url = "http://amzn.to/1eXLEJF",
    cover = {amazon = "51MRTzB7tKL"},
    authors = {"Brant Cooper"},
  },
  {
    title = "Small Giants",
    url = "http://amzn.to/1aITLom",
    cover = {amazon = "41w5o5WZ5TL"},
    authors = {"Bo Burlingham"},
  },
  {
    title = "Predictable Revenue",
    url = "http://amzn.to/1hj2f7h",
    cover = {amazon = "51mYrIgNB6L"},
    authors = {"Aaron Ross"},
  },
  {
    title = "The Hacker's Guide to Passive Income",
    url = "https://leanpub.com/passiveincome",
    cover = "imgs/passiveincome.jpg",
    authors = {"Myles Recny"},
  },
  {
    title = "Remote: Office Not Required",
    url = "http://amzn.to/JQbgLS",
    cover = {amazon = "41BGy1UQYpL"},
    authors = {"David Heinemeier Hansson", "Jason Fried"},
  },
  {
    title = "Hatching Twitter",
    url = "http://amzn.to/JQbrqH",
    cover = {amazon = "51rxeahPPKL"},
    authors = {"Nick Bilton"},
  },
  {
    title = "In the Plex",
    url = "http://amzn.to/1i8bzzK",
    cover = {amazon = "419mago3QtL"},
    authors = {"Steven Levy"},
  },
  {
    title = "En Amazonie",
    url = "http://amzn.to/192QT7c",
    cover = {amazon = "31vm2yjkpeL"},
    authors = {"Jean-Baptiste Malet"},
  },
  {
    title = "The Hard Thing About Hard Things",
    url = "http://amzn.to/1joCE34",
    cover = {amazon = "51yomjzxUDL"},
    authors = {"Ben Horowitz"},
  },
  {
    title = "39 Bootstrapped Side Projects",
    url = "http://www.sideprojectbook.com/",
    cover = "imgs/sideprojects.jpg",
    authors = {"Laksman"},
  },
  {
    title = "Creativity, Inc",
    url = "http://amzn.to/1joEzV3",
    cover = {amazon = "41xs4vbcTPL"},
    authors = {"Ed Catmull"},
  },
  {
    title = "iWoz",
    url = "http://amzn.to/1lxHTZW",
    cover = {amazon = "41kqWgJtKoL"},
    authors = {"Steve Wozniak"},
  },
  {
    title = "How to Castrate a Bull",
    url = "http://amzn.to/1jTpPgu",
    cover = {amazon = "41mLZiARg1L"},
    authors = {"Dave Hitz"},
  },
  {
    title = "Delivering Happiness",
    url = "http://amzn.to/1j6gXDw",
    cover = {amazon = "51vNDc50J3L"},
    authors = {"Tony Hsieh"},
  },
  {
    title = "Game Over: How Nintendo Conquered The World",
    url = "http://amzn.to/1jTq9eV",
    cover = {amazon = "41V46E9iHOL"},
    authors = {"David Sheff"},
  },
  {
    title = "Business Adventures: Twelve Classic Tales from the World of Wall Street",
    url = "http://amzn.to/VOtna9",
    cover = {amazon = "51bIUWoud2L"},
    authors = {"John Brooks"},
  },
  {
    title = "Burn Rate: How I Survived the Gold Rush Years on the Internet",
    url = "http://amzn.to/1lsvAVk",
    cover = {amazon = "51GqUybH2rL"},
    authors = {"Michael Wolff"},
  },
  {
    title = "The New New Thing: A Silicon Valley Story",
    url = "http://amzn.to/1p9Zuhv",
    cover = {amazon = "41NZwcdz2TL"},
    authors = {"Michael Lewis"},
  },
  {
    title = "Traction: A Startup Guide to Getting Customers",
    url = "http://amzn.to/1O4yAzj",
    cover = {amazon = "51E39T7ITjL"},
    authors = {"Gabriel Weinberg", "Justin Mares"},
  },
  {
    title = "Mainstream",
    url = "http://www.amazon.fr/Mainstream-Frédéric-Martel/dp/2081236176",
    cover = {amazon = "413vBy6NRhL"},
    authors = {"Frédéric Martel"},
  },
  {
    title = "The Halo Effect",
    url = "http://amzn.to/Zqe2In",
    cover = {amazon = "51e7JJowhxL"},
    authors = {"Phil Rosenzweig"},
  },
  {
    title = "Gödel, Escher, Bach",
    url = "http://amzn.to/11cY8UH",
    cover = {amazon = "41FWhmVlAJL"},
    authors = {"Douglas R. Hofstadter"},
  },
  {
    title = "I am a Strange Loop",
    url = "http://amzn.to/117h1XW",
    cover = {amazon = "51tGI27TXlL"},
    authors = {"Douglas R. Hofstadter"},
  },
  {
    title = "Reasons and Persons",
    url = "http://amzn.to/ZqegiO",
    cover = {amazon = "41szIEA3EJL"},
    authors = {"Derek Parfit"},
  },
  {
    title = "Thinking, Fast and Slow",
    url = "http://amzn.to/128Gx1w",
    cover = {amazon = "41fo1J7iiFL"},
    authors = {"Daniel Kahneman"},
  },
  {
    title = "The Flinch",
    url = "http://amzn.to/1333ySk",
    cover = {amazon = "611Nc1aUuUL"},
    authors = {"Julien Smith"},
  },
  {
    title = "A New Kind Of Science",
    url = "http://amzn.to/YFwNvC",
    cover = {amazon = "51lIOlIxlzL"},
    authors = {"Stephen Wolfram"},
  },
  {
    title = "Petite mathématique du cerveau",
    url = "http://www.amazon.com/gp/product/B009G9BFHS",
    cover = {amazon = "41q-qwyg88L"},
    authors = {"Claude Berrou", "Vincent Gripon"},
  },
  {
    title = "Influence: The Psychology of Persuasion",
    url = "http://amzn.to/ZUqejw",
    cover = {amazon = "51rZPhIJD6L"},
    authors = {"Robert B. Cialdini"},
  },
  {
    title = "Race Against the Machine",
    url = "http://amzn.to/18qaoVC",
    cover = {amazon = "51tMnMC05LL"},
    authors = {"Erik Brynjolfsson"},
  },
  {
    title = "Even a Geek Can Speak",
    url = "http://amzn.to/151THzu",
    cover = {amazon = "51grNPH4huL"},
    authors = {"Joey Asher"},
  },
  {
    title = "Taking Smart Risks",
    url = "http://amzn.to/16eJ1yn",
    cover = {amazon = "51eWxoalIXL"},
    authors = {"Doug Sundheim"},
  },
  {
    title = "Invisible Engines",
    url = "http://amzn.to/15Jqdnc",
    cover = {amazon = "41Pk2Vm%2B3ZL"},
    authors = {"David S. Evans"},
  },
  {
    title = "Coding Places: Software Practice in a South American City",
    url = "http://amzn.to/1i8crVd",
    cover = {amazon = "51153HkFACL"},
    authors = {"Yuri Takhteyev"},
  },
  {
    title = "Punished by Rewards",
    url = "http://amzn.to/1zuaTcj",
    cover = {amazon = "51pCDvQwC9L"},
    authors = {"Alfie Kohn"},
  },
  {
    title = "Irrational Exuberance",
    url = "http://amzn.to/1qHuSzv",
    cover = {amazon = "51B0l-Nu13L"},
    authors = {"Robert J. Shiller"},
  },
  {
    title = "La France en Réseaux, tome 1",
    url = "http://www.amazon.fr/réseaux-rencontre-télécommunications-informatique-1960-1980/dp/2363670124",
    cover = {amazon = "31efaS-vAPL"},
    authors = {"Valérie Schafer"},
  },
  {
    title = "Confession d'un voleur",
    url = "http://www.confessions-voleur.net/",
    cover = {amazon = "411EJP3Z1NL"},
    authors = {"Laurent Chemla"},
  },
  {
    title = "One Click: Jeff Bezos and the Rise of Amazon.com",
    url = "http://amzn.to/11cZH4U",
    cover = {amazon = "31pB1TvLyRL"},
    authors = {"Richard L. Brandt"},
  },
  {
    title = "Walt Disney: The Triumph of the American Imagination",
    url = "http://amzn.to/10V8Gq7",
    cover = {amazon = "51VQffdB9iL"},
    authors = {"Neal Gabler"},
  },
  {
    title = "Masters of Doom: How Two Guys Created an Empire and Transformed Pop Culture",
    url = "http://amzn.to/111V0uQ",
    cover = {amazon = "31Kj8mg%2BSFL"},
    authors = {"David Kushner"},
  },
  {
    title = "The Fractalist: Memoir of a Scientific Maverick",
    url = "http://amzn.to/11d0fYu",
    cover = {amazon = "41fdS%2BV%2ByQL"},
    authors = {"Benoit Mandelbrot"},
  },
  {
    title = "The Black Swan: The Impact of the Highly Improbable",
    url = "http://amzn.to/ZUqLC9",
    cover = {amazon = "41arGbyxTcL"},
    authors = {"Nassim Nicholas Taleb"},
  },
  {
    title = "Antifragile: Things That Gain from Disorder",
    url = "http://amzn.to/128IfQh",
    cover = {amazon = "41k-qVD7rvL"},
    authors = {"Nassim Nicholas Taleb"},
  },
  {
    title = "Tubes: A Journey to the Center of the Internet",
    url = "http://amzn.to/11d0Mtv",
    cover = {amazon = "613R9BEJ1OL"},
    authors = {"Andrew Blum"},
  },
  {
    title = "Understanding Power",
    url = "http://amzn.to/128IFpW",
    cover = {amazon = "41ZEGrrtDBL"},
    authors = {"Noam Chomsky"},
  },
  {
    title = "You Are Not A Gadget: A Manifesto",
    url = "http://amzn.to/128IMSs",
    cover = {amazon = "51bpl1wA%2BaL"},
    authors = {"Jaron Lanier"},
  },
  {
    title = "Value, Price and Profit",
    url = "http://amzn.to/18xf1N9",
    cover = {amazon = "51xiu3lYggL"},
    authors = {"Karl Marx"},
  },
  {
    title = "Anarchy Evolution",
    url = "http://amzn.to/17Fx1EQ",
    cover = {amazon = "51%2B1D0SGE-L"},
    authors = {"Greg Graffin"},
  },
  {
    title = "Rise of the Videogame Zinesters",
    url = "http://amzn.to/14oJOtS",
    cover = {amazon = "61nVEs7BhqL"},
    authors = {"Anna Anthropy"},
  },
  {
    title = "Softwar: An Intimate Portrait of Larry Ellison and Oracle",
    url = "http://amzn.to/J2KwXS",
    cover = {amazon = "51iIe7h8TnL"},
    authors = {"Matthew Symonds"},
  },
  {
    title = "Small Is Beautiful: Economics as if People Mattered",
    url = "http://amzn.to/19CPS6j",
    cover = {amazon = "51a%2B9Zv0fmL"},
    authors = {"E. F. Schumacher"},
  },
  {
    title = "Winner Take All: How Competitiveness Shapes the Fate of Nations",
    url = "http://amzn.to/19CYfyG",
    cover = {amazon = "41WaYtF-eAL"},
    authors = {"Richard Elkus"},
  },
  {
    title = "The Box: How the Shipping Container Made the World Smaller and the World Economy Bigger",
    url = "http://amzn.to/JQphJz",
    cover = {amazon = "51%2BUJhYyHxL"},
    authors = {"Marc Levinson"},
  },
  {
    title = "The Most Powerful Idea in the World: A Story of Steam, Industry, and Invention",
    url = "http://amzn.to/JQpzAf",
    cover = {amazon = "51MHstcCOTL"},
    authors = {"William Rosen"},
  },
  {
    title = "Freedom and the Law",
    url = "http://amzn.to/1jTmEW1",
    cover = {amazon = "41Y%2Bc2%2BBDmL"},
    authors = {"Bruno Leoni"},
  },
  {
    title = "Technological Revolutions and Financial Capital: The Dynamics of Bubbles and Golden Ages",
    url = "http://amzn.to/1qcLAJN",
    cover = {amazon = "51O8T-shCgL"},
    authors = {"Carlota Perez"},
  },
  {
    title = "Manna: Two Visions of Humanity's Future",
    url = "http://amzn.to/ZZFNh4",
    cover = {amazon = "41hMlrD%2BQ7L"},
    authors = {"Marshall Brain"},
  },
  {
    title = "Snow Crash",
    url = "http://amzn.to/179hqLr",
    cover = {amazon = "5192EnTxNQL"},
    authors = {"Neal Stephenson"},
  },
  {
    title = "Neuromancer",
    url = "http://amzn.to/11d1Tcv",
    cover = {amazon = "51VF20SWCZL"},
    authors = {"William Gibson"},
  },
  {
    title = "Cryptonomicon",
    url = "http://amzn.to/117jodk",
    cover = {amazon = "51aC-j3u7ZL"},
    authors = {"Neal Stephenson"},
  },
  {
    title = "The Diamond Age",
    url = "http://amzn.to/15drarL",
    cover = {amazon = "51eDiMq4dsL"},
    authors = {"Neal Stephenson"},
  },
  {
    title = "The Shockwave Rider",
    url = "http://amzn.to/19RCbOW",
    cover = {amazon = "41EgppJREYL"},
    authors = {"John Brunner"},
  },
  {
    title = "The Minority Report and Other Classic Stories",
    url = "http://amzn.to/17RJhpf",
    cover = {amazon = "511LyfwPPkL"},
    authors = {"Philip K. Dick"},
  },
  {
    title = "Solar Lottery",
    url = "http://amzn.to/19REamp",
    cover = {amazon = "410Wr6gd-BL"},
    authors = {"Philip K. Dick"},
  },
  {
    title = "Do Androids Dream of Electric Sheep?",
    url = "http://amzn.to/19Uiz04",
    cover = {amazon = "51figp%2BFE8L"},
    authors = {"Philip K. Dick"},
  },
  {
    title = "Chronicles of Amber",
    url = "http://amzn.to/19UiMQR",
    cover = {amazon = "61G4E6ztjML"},
    authors = {"Roger Zelazny"},
  },
  {
    title = "Wang, tome 1 : Les Portes d'Occident",
    url = "http://amzn.to/13jVUIf",
    cover = {amazon = "51ZHB9EKSRL"},
    authors = {"Pierre Bordage"}
  },
  {
    title = "Wang, tome 2 : Les Aigles d'Orient",
    url = "http://amzn.to/121vAMF",
    cover = {amazon = "514ZKHV6GHL"},
    authors = {"Pierre Bordage"}
  },
  {
    title = "River Town",
    url = "http://amzn.to/18qdc4Z",
    cover = {amazon = "515KBH9QMZL"},
    authors = {"Peter Hessler"}
  },
  {
    title = "Daemon",
    url = "http://amzn.to/1lxGkuQ",
    cover = {amazon = "51NFhTaIdnL"},
    authors = {"Daniel Suarez"}
  },
  {
    title = "Free Culture: The Nature and Future of Creativity",
    url = "http://amzn.to/1NuEX3Q",
    cover = {amazon = "51jdNhywcoL"},
    authors = {"Lawrence Lessig"},
  },
  {
    title = "Inside Apple",
    url = "http://amzn.to/1CKYCRE",
    cover = {amazon = "41pAcnGheDL"},
    authors = {"Adam Lashinsky"},
  },
  {
    title = "Hidden in Plain Sight",
    url = "http://amzn.to/1HijN3Z",
    cover = {amazon = "51K1-n02wiL"},
    authors = {"Jan Chipchase"},
  },
  {
    title = "The Back of the Napkin",
    url = "http://amzn.to/1aGp74m",
    cover = {amazon = "615o1FL8lAL"},
    authors = {"Dan Roam"},
  },
  {
    title = "Cryptography Engineering",
    url = "http://amzn.to/1JC8TW3",
    cover = {amazon = "51SEhLArm%2BL"},
    authors = {"Niels Ferguson", "Bruce Schneier", "Tadayoshi Kohno"},
  },
  {
    title = "Secure Coding in C and C++ (2nd Edition)",
    url = "http://amzn.to/1JC8WRB",
    cover = {amazon = "51V0zW12pmL"},
    authors = {"Robert C. Seacord"},
  },
  {
    title = "The Mom Test",
    url = "http://amzn.to/1HikaeJ",
    cover = {amazon = "41IbI8-5wiL"},
    authors = {"Rob Fitzpatrick"},
  },
  {
    title = "La France sans ses usines",
    url = "http://www.amazon.com/gp/product/B005ZPM0W6",
    cover = {amazon = "41h1VHnZ5bL"},
    authors = {"Patrick Artus", "Marie-Paule Virard"},
  },
  {
    title = "Zero to One",
    url = "http://amzn.to/1HikjyO",
    cover = {amazon = "411YBdZVAPL"},
    authors = {"Peter Thiel", "Blake Masters"},
  },
  {
    title = "The HP Way",
    url = "http://amzn.to/1HikmuJ",
    cover = {amazon = "51BHVVG2EQL"},
    authors = {"David Packard"},
  },
  {
    title = "Behind the Cloud",
    url = "http://amzn.to/1FMUOnl",
    cover = {amazon = "51f60FQ2k%2BL"},
    authors = {"Marc Benioff"},
  },
  {
    title = "Trust Me, I'm Lying",
    url = "http://amzn.to/1CL0KJo",
    cover = {amazon = "51-45Wg43WL"},
    authors = {"Ryan Holiday"},
  },
  {
    title = "An Introduction to Japanese Society ",
    url = "http://amzn.to/1HikxpP",
    cover = {amazon = "51AKubLiCZL"},
    authors = {"Yoshio Sugimoto"},
  },
  {
    title = "La voix de l'inconscient",
    url = "http://amzn.to/1O4Az6L",
    cover = {amazon = "51x9hFsSl5L"},
    authors = {"Jean-Emmanuel Combe"},
  },
  {
    title = "The Peripheral",
    url = "http://amzn.to/1GBs8R7",
    cover = {amazon = "41jaIvZfiML"},
    authors = {"William Gibson"},
  },
  {
    title = "The Practice of Programming",
    url = "http://amzn.to/1DVFvvg",
    cover = {amazon = "51a1SwDTnYL"},
    authors = {"Brian W. Kernighan", "Rob Pike"},
  },
  {
    title = "The Year Without Pants",
    url = "http://amzn.to/1NuJ5AR",
    cover = {amazon = "510LrJroP0L"},
    authors = {"Scott Berkun"},
  },
  {
    title = "The Big Switch: Rewiring the World, from Edison to Google",
    url = "http://amzn.to/1DzLWln",
    cover = {amazon = "515vyL3hKSL"},
    authors = {"Nicholas Carr"},
  },
  {
    title = "The Rational Optimist",
    url = "http://amzn.to/1HilkXK",
    cover = {amazon ="41gqiO01CcL"},
    authors = {"Matt Ridley"},
  },
  {
    title = "The Reasoned Schemer",
    url = "http://amzn.to/1Hilo9Y",
    cover = {amazon = "515dld8Y6IL"},
    authors = {"Daniel P. Friedman", "William E. Byrd", "Oleg Kiselyov"},
  },
  {
    title = "The Bite in the Apple",
    url = "http://amzn.to/1HilApz",
    cover = {amazon = "51RknJoxSNL"},
    authors = {"Chrisann Brennan"},
  },
  {
    title = "The Nature of Software Development",
    url = "http://amzn.to/1GBt6gj",
    cover = {amazon = "51Ehd9aWRGL"},
    authors = {"Ron Jeffries"},
  },
  {
    title = "Seeing like a State",
    url = "http://amzn.to/1OpJnGe",
    cover = {amazon = "41wNdayiE2L"},
    authors = {"James C. Scott"},
  },
  {
    title = "The Systems Bible (Systemantics)",
    url = "http://amzn.to/1NuKgQO",
    cover = {amazon = "417jBDgaQuL"},
    authors = {"John Gall"},
  },
  {
    title = "Building Microservices ",
    url = "http://amzn.to/1GBtrzA",
    cover = {amazon = "5128sKZpo%2BL"},
    authors = {"Sam Newman"},
  },
  {
    title = "Emergence",
    url = "http://amzn.to/1DzMzeU",
    cover = {amazon = "51Ktqfzh10L"},
    authors = {"Steven Johnson"},
  },
  {
    title = "The Four Steps to the Epiphany ",
    url = "http://amzn.to/1Himm61",
    cover = {amazon = "51MLvC%2BJryL"},
    authors = {"Steve Blank"},
  },
  {
    title = "Slicing Pie",
    url = "http://amzn.to/1DVGmvJ",
    cover = {amazon = "31We80f2z1L"},
    authors = {"Mike Moyer"},
  },
  {
    title = "Spent: Sex, Evolution, and Consumer Behavior ",
    url = "http://amzn.to/1NuL345",
    cover = {amazon = "413TFIj93kL"},
    authors = {"Geoffrey Miller"},
  },
}
